ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫0
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:34 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:34 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for StockStats
ERROR fetch_stocks.py:34 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for DFCFStockInfo
ERROR fetch_stocks.py:34 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫8
ERROR fetch_stocks.py:34 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for DFCFStockInfo
ERROR fetch_stocks.py:34 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for DFCFStockInfo
ERROR fetch_stocks.py:34 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for DFCFStockInfo
ERROR fetch_stocks.py:35 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'int' object is not iterable
ERROR fetch_stocks.py:36 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'int' object is not iterable
ERROR fetch_stocks.py:37 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'int' object is not iterable
ERROR fetch_stocks.py:37 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'int' object is not iterable
ERROR fetch_stocks.py:37 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'int' object is not iterable
ERROR fetch_stocks.py:37 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Cannot index by location index with a non-integer key
ERROR fetch_stocks.py:37 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for DFCFStockInfo
ERROR fetch_stocks.py:37 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for DFCFStockInfo
ERROR fetch_stocks.py:37 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'username' is an invalid keyword argument for DFCFStockInfo
ERROR fetch_stocks.py:35 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'str' object has no attribute 'f2'
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫'dict' object has no attribute 'f2'
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
ERROR fetch_stocks.py:33 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() missing 1 required positional argument: 'email'
ERROR fetch_stocks.py:35 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR __init__.py:113 Error: Directory migrations already exists and is not empty
ERROR fetch_stocks.py:35 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR fetch_stocks.py:35 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
ERROR fetch_stocks.py:36 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:19 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 22:12:48.275284 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:22 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11989855766296387 √Î #######
INFO execute_daily_job.py:19 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 22:17:28.401338 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:22 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.12099719047546387 √Î #######
INFO execute_daily_job.py:19 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 22:20:41.108070 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:22 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11515116691589355 √Î #######
INFO execute_daily_job.py:19 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 22:23:12.485906 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:22 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.10639548301696777 √Î #######
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO _internal.py:97  * Restarting with stat
WARNING _internal.py:97  * Debugger is active!
INFO _internal.py:97  * Debugger PIN: 227-920-992
INFO _internal.py:97  * Detected change in 'd:\\work\\instock\\core\\models.py', reloading
INFO _internal.py:97  * Restarting with stat
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO execute_daily_job.py:19 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:34:06.556527 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
INFO execute_daily_job.py:22 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.10641217231750488 √Î #######
INFO execute_daily_job.py:19 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:35:23.447721 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
INFO execute_daily_job.py:22 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.10364603996276855 √Î #######
INFO execute_daily_job.py:19 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:36:23.263560 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
INFO execute_daily_job.py:22 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11315131187438965 √Î #######
INFO execute_daily_job.py:19 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:37:48.882075 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:22 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11860084533691406 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:38:17.518398 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11441421508789062 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:38:51.451290 #######
ERROR fetch_stocks.py:29 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11235189437866211 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:40:37.495321 #######
ERROR fetch_stocks.py:30 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11170744895935059 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:41:27.662241 #######
ERROR fetch_stocks.py:30 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.12413167953491211 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:41:45.370641 #######
ERROR fetch_stocks.py:30 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.10827970504760742 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:42:54.789282 #######
ERROR fetch_stocks.py:30 stockfetch.fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.09645509719848633 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:44:49.749122 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11053991317749023 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:47:31.482264 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.10045552253723145 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:48:00.079105 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11481118202209473 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:48:13.726037 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0972754955291748 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-15 23:48:59.061506 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.10180783271789551 √Î #######
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 00:01:16.822239 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.10072755813598633 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 00:01:20.483932 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.09970569610595703 √Î #######
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 14:40:37.403790 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.1029360294342041 √Î #######
INFO execute_daily_job.py:21 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 14:49:30.116060 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:24 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:20:14.552482 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0019686222076416016 √Î #######
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO _internal.py:97  * Restarting with stat
WARNING _internal.py:97  * Debugger is active!
INFO _internal.py:97  * Debugger PIN: 111-205-193
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:26:22.713785 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0019991397857666016 √Î #######
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:28:32.296702 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0 √Î #######
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:32:32.949899 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0 √Î #######
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:32:45.630241 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:33:32.080003 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:33:42.489878 #######
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:34:11.465639 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:34:52.287097 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.0 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:35:16.200697 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.2827448844909668 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:35:23.692430 #######
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.10435843467712402 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:35:54.753219 #######
ERROR fetch_stocks.py:29 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.12044644355773926 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:36:10.269124 #######
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.12263131141662598 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:37:34.271599 #######
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11655974388122559 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:37:54.210580 #######
ERROR fetch_stocks.py:29 fetch_stocks¥¶¿Ì“Ï≥££∫Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.
INFO execute_daily_job.py:25 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11334347724914551 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:39:07.276015 #######
INFO execute_daily_job.py:26 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.12339377403259277 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:39:15.390912 #######
ERROR fetch_stocks.py:29 fetch_stocks¥¶¿Ì“Ï≥££∫The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
INFO execute_daily_job.py:26 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.1202843189239502 √Î #######
INFO execute_daily_job.py:22 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:39:49.172925 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫The current Flask app is not registered with this 'SQLAlchemy' instance. Did you forget to call 'init_app', or did you create multiple 'SQLAlchemy' instances?
INFO execute_daily_job.py:26 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.11805415153503418 √Î #######
INFO execute_daily_job.py:24 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:42:12.590200 #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO _internal.py:97  * Restarting with stat
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
WARNING _internal.py:97  * Debugger is active!
INFO _internal.py:97  * Debugger PIN: 111-205-193
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO _internal.py:97 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO _internal.py:97 [33mPress CTRL+C to quit[0m
INFO _internal.py:97  * Restarting with stat
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
WARNING _internal.py:97  * Debugger is active!
INFO _internal.py:97  * Debugger PIN: 111-205-193
INFO _internal.py:97  * Detected change in 'd:\\workspace\\stock\\core\\__init__.py', reloading
INFO _internal.py:97  * Restarting with stat
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
WARNING _internal.py:97  * Debugger is active!
INFO _internal.py:97  * Debugger PIN: 111-205-193
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:24 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:48:25.361195 #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:51:06.599444 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'date' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': None, 'f2': None, 'f3': None, 'f4': None, 'f5': None, 'f6': None, 'f7': None, 'f8': None, 'f10': None, 'f11': None, 'f12': None, 'f13': None, 'f14': None, 'f15': None, 'f16': None, 'f17': None, 'f18': None, 'f20': None, 'f21': None, 'f22': None, 'f23': None, 'f24': None, 'f25': None, 'f26': None, 'f37': None, 'f38': None, 'f39': None, 'f40': None, 'f41': None, 'f45': None, 'f46': None, 'f48': None, 'f49': None, 'f57': None, 'f61': None, 'f100': None, 'f112': None, 'f113': None, 'f114': None, 'f115': None, 'f221': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.5550236701965332 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 15:56:54.783711 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'date' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': None, 'f2': None, 'f3': None, 'f4': None, 'f5': None, 'f6': None, 'f7': None, 'f8': None, 'f10': None, 'f11': None, 'f12': None, 'f13': None, 'f14': None, 'f15': None, 'f16': None, 'f17': None, 'f18': None, 'f20': None, 'f21': None, 'f22': None, 'f23': None, 'f24': None, 'f25': None, 'f26': None, 'f37': None, 'f38': None, 'f39': None, 'f40': None, 'f41': None, 'f45': None, 'f46': None, 'f48': None, 'f49': None, 'f57': None, 'f61': None, 'f100': None, 'f112': None, 'f113': None, 'f114': None, 'f115': None, 'f221': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.22261595726013184 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:03:23.684176 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'date' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': None, 'f2': None, 'f3': None, 'f4': None, 'f5': None, 'f6': None, 'f7': None, 'f8': None, 'f10': None, 'f11': None, 'f12': None, 'f13': None, 'f14': None, 'f15': None, 'f16': None, 'f17': None, 'f18': None, 'f20': None, 'f21': None, 'f22': None, 'f23': None, 'f24': None, 'f25': None, 'f26': None, 'f37': None, 'f38': None, 'f39': None, 'f40': None, 'f41': None, 'f45': None, 'f46': None, 'f48': None, 'f49': None, 'f57': None, 'f61': None, 'f100': None, 'f112': None, 'f113': None, 'f114': None, 'f115': None, 'f221': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.23067712783813477 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:05:47.346491 #######
ERROR fetch_stocks.py:29 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'date' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': None, 'f2': None, 'f3': None, 'f4': None, 'f5': None, 'f6': None, 'f7': None, 'f8': None, 'f10': None, 'f11': None, 'f12': None, 'f13': None, 'f14': None, 'f15': None, 'f16': None, 'f17': None, 'f18': None, 'f20': None, 'f21': None, 'f22': None, 'f23': None, 'f24': None, 'f25': None, 'f26': None, 'f37': None, 'f38': None, 'f39': None, 'f40': None, 'f41': None, 'f45': None, 'f46': None, 'f48': None, 'f49': None, 'f57': None, 'f61': None, 'f100': None, 'f112': None, 'f113': None, 'f114': None, 'f115': None, 'f221': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.22663116455078125 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:06:08.045814 #######
ERROR fetch_stocks.py:29 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'date' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': None, 'f2': None, 'f3': None, 'f4': None, 'f5': None, 'f6': None, 'f7': None, 'f8': None, 'f10': None, 'f11': None, 'f12': None, 'f13': None, 'f14': None, 'f15': None, 'f16': None, 'f17': None, 'f18': None, 'f20': None, 'f21': None, 'f22': None, 'f23': None, 'f24': None, 'f25': None, 'f26': None, 'f37': None, 'f38': None, 'f39': None, 'f40': None, 'f41': None, 'f45': None, 'f46': None, 'f48': None, 'f49': None, 'f57': None, 'f61': None, 'f100': None, 'f112': None, 'f113': None, 'f114': None, 'f115': None, 'f221': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.221818208694458 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:06:44.477029 #######
ERROR fetch_stocks.py:29 fetch_stocks¥¶¿Ì“Ï≥££∫__init__() takes 1 positional argument but 2 were given
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.1766054630279541 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:07:08.516350 #######
ERROR fetch_stocks.py:29 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'date' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': None, 'f2': None, 'f3': None, 'f4': None, 'f5': None, 'f6': None, 'f7': None, 'f8': None, 'f10': None, 'f11': None, 'f12': None, 'f13': None, 'f14': None, 'f15': None, 'f16': None, 'f17': None, 'f18': None, 'f20': None, 'f21': None, 'f22': None, 'f23': None, 'f24': None, 'f25': None, 'f26': None, 'f37': None, 'f38': None, 'f39': None, 'f40': None, 'f41': None, 'f45': None, 'f46': None, 'f48': None, 'f49': None, 'f57': None, 'f61': None, 'f100': None, 'f112': None, 'f113': None, 'f114': None, 'f115': None, 'f221': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.24581217765808105 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:08:25.553688 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'date' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': None, 'f2': None, 'f3': None, 'f4': None, 'f5': None, 'f6': None, 'f7': None, 'f8': None, 'f10': None, 'f11': None, 'f12': None, 'f13': None, 'f14': None, 'f15': None, 'f16': None, 'f17': None, 'f18': None, 'f20': None, 'f21': None, 'f22': None, 'f23': None, 'f24': None, 'f25': None, 'f26': None, 'f37': None, 'f38': None, 'f39': None, 'f40': None, 'f41': None, 'f45': None, 'f46': None, 'f48': None, 'f49': None, 'f57': None, 'f61': None, 'f100': None, 'f112': None, 'f113': None, 'f114': None, 'f115': None, 'f221': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.24212884902954102 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:09:02.293458 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'date' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': None, 'f2': None, 'f3': None, 'f4': None, 'f5': None, 'f6': None, 'f7': None, 'f8': None, 'f10': None, 'f11': None, 'f12': None, 'f13': None, 'f14': None, 'f15': None, 'f16': None, 'f17': None, 'f18': None, 'f20': None, 'f21': None, 'f22': None, 'f23': None, 'f24': None, 'f25': None, 'f26': None, 'f37': None, 'f38': None, 'f39': None, 'f40': None, 'f41': None, 'f45': None, 'f46': None, 'f48': None, 'f49': None, 'f57': None, 'f61': None, 'f100': None, 'f112': None, 'f113': None, 'f114': None, 'f115': None, 'f221': None}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.20952534675598145 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:17:39.742127 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫__init__() got an unexpected keyword argument 'f2'
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.16069722175598145 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:17:56.279219 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫'f9' is an invalid keyword argument for DFCFStockInfo
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.19208621978759766 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:20:20.370296 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.OperationalError) (1054, "Unknown column 'f9' in 'field list'")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.24437212944030762 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 16:23:15.313750 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.OperationalError) (1054, "Unknown column 'f9' in 'field list'")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.22796916961669922 √Î #######
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO utils.py:148 Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO utils.py:161 NumExpr defaulting to 8 threads.
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:18:13.129768 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.OperationalError) (1054, "Unknown column 'f9' in 'field list'")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.256986141204834 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:34:02.359704 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.OperationalError) (1054, "Unknown column 'f9' in 'field list'")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.2273426055908203 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:34:48.230764 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'f13' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.21468853950500488 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:36:09.820233 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.IntegrityError) (1048, "Column 'f13' cannot be null")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.22965383529663086 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:36:47.467525 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.DataError) (1265, "Data truncated for column 'f14' at row 1")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.21163225173950195 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:49:46.890980 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.DataError) (1265, "Data truncated for column 'f100' at row 1")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.20195436477661133 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:50:14.991298 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.DataError) (1265, "Data truncated for column 'f100' at row 1")
[SQL: INSERT INTO stock_info (date, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f12, f13, f14, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f12)s, %(f13)s, %(f14)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f2': 0.11, 'f3': 22.22, 'f4': 0.02, 'f5': 4413102, 'f6': 46894947.07, 'f7': 22.22, 'f8': 10.75, 'f9': -4.97, 'f10': 1.83, 'f11': 0.0, 'f12': '300116', 'f13': None, 'f14': '*ST±£¡¶', 'f15': 0.11, 'f16': 0.09, 'f17': 0.09, 'f18': 0.09, 'f20': 486815050, 'f21': 451423177, 'f22': 0.0, 'f23': 2.75, 'f24': -90.0, 'f25': -92.57, 'f26': 20100902, 'f37': -13.68, 'f38': 4425591367.0, 'f39': 4103847062.0, 'f40': 25725494.11, 'f41': -29.2828267368, 'f45': -24506261.74, 'f46': -169.126466179145, 'f48': -1.705464236231, 'f49': -59.5282033244, 'f57': 61.5423845407, 'f61': 0.749391668765, 'f100': 'µÁ≥ÿ', 'f112': -0.005537398, 'f113': 0.040043472, 'f114': -2.59, 'f115': -2.39, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.2129194736480713 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:50:21.957408 #######
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.20540499687194824 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:51:08.636280 #######
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.24074649810791016 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:51:40.723382 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.DataError) (1265, "Data truncated for column 'f112' at row 1")
[SQL: INSERT INTO stock_info (date, f12, f14, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f13, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f12)s, %(f14)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f13)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f12': '837023', 'f14': '∞≈ﬁ±π…∑›', 'f2': 14.1, 'f3': 6.66, 'f4': 0.88, 'f5': 39621, 'f6': 53671695.73, 'f7': 8.32, 'f8': 16.56, 'f9': 38.16, 'f10': 0.71, 'f11': 1.22, 'f13': None, 'f15': 14.1, 'f16': 13.0, 'f17': 13.31, 'f18': 13.22, 'f20': 1209780000, 'f21': 337420797, 'f22': 0.0, 'f23': 3.26, 'f24': 34.29, 'f25': 34.29, 'f26': 20240329, 'f37': 2.39, 'f38': 85800000.0, 'f39': 23930553.0, 'f40': 115598233.26, 'f41': 19.001709731, 'f45': 7924933.74, 'f46': 10.578060034694, 'f48': 0.0, 'f49': 31.7204416676, 'f57': 44.8863957999, 'f61': 0.0, 'f100': 'ªØ—ß÷∆∆∑', 'f112': '-', 'f113': 4.328377241, 'f114': 29.39, 'f115': 28.86, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 4.316914796829224 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:55:48.758552 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.DataError) (1265, "Data truncated for column 'f112' at row 1")
[SQL: INSERT INTO stock_info (date, f12, f14, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f13, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f12)s, %(f14)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f13)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f12': '837023', 'f14': '∞≈ﬁ±π…∑›', 'f2': 14.1, 'f3': 6.66, 'f4': 0.88, 'f5': 39621, 'f6': 53671695.73, 'f7': 8.32, 'f8': 16.56, 'f9': 38.16, 'f10': 0.71, 'f11': 1.22, 'f13': None, 'f15': 14.1, 'f16': 13.0, 'f17': 13.31, 'f18': 13.22, 'f20': 1209780000, 'f21': 337420797, 'f22': 0.0, 'f23': 3.26, 'f24': 34.29, 'f25': 34.29, 'f26': 20240329, 'f37': 2.39, 'f38': 85800000.0, 'f39': 23930553.0, 'f40': 115598233.26, 'f41': 19.001709731, 'f45': 7924933.74, 'f46': 10.578060034694, 'f48': 0.0, 'f49': 31.7204416676, 'f57': 44.8863957999, 'f61': 0.0, 'f100': 'ªØ—ß÷∆∆∑', 'f112': '-', 'f113': 4.328377241, 'f114': 29.39, 'f115': 28.86, 'f221': 20240331}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 4.104647159576416 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 17:57:09.004646 #######
ERROR fetch_stocks.py:30 fetch_stocks¥¶¿Ì“Ï≥££∫(pymysql.err.DataError) (1265, "Data truncated for column 'f2' at row 1")
[SQL: INSERT INTO stock_info (date, f12, f14, f2, f3, f4, f5, f6, f7, f8, f9, f10, f11, f13, f15, f16, f17, f18, f20, f21, f22, f23, f24, f25, f26, f37, f38, f39, f40, f41, f45, f46, f48, f49, f57, f61, f100, f112, f113, f114, f115, f221) VALUES (%(date)s, %(f12)s, %(f14)s, %(f2)s, %(f3)s, %(f4)s, %(f5)s, %(f6)s, %(f7)s, %(f8)s, %(f9)s, %(f10)s, %(f11)s, %(f13)s, %(f15)s, %(f16)s, %(f17)s, %(f18)s, %(f20)s, %(f21)s, %(f22)s, %(f23)s, %(f24)s, %(f25)s, %(f26)s, %(f37)s, %(f38)s, %(f39)s, %(f40)s, %(f41)s, %(f45)s, %(f46)s, %(f48)s, %(f49)s, %(f57)s, %(f61)s, %(f100)s, %(f112)s, %(f113)s, %(f114)s, %(f115)s, %(f221)s)]
[parameters: {'date': '2024-05-16', 'f12': '688555', 'f14': 'ÕÀ –‘Û¥Ô', 'f2': '-', 'f3': '-', 'f4': '-', 'f5': '-', 'f6': '-', 'f7': '-', 'f8': 0.0, 'f9': '-', 'f10': '-', 'f11': '-', 'f13': None, 'f15': '-', 'f16': '-', 'f17': '-', 'f18': 1.12, 'f20': '-', 'f21': '-', 'f22': '-', 'f23': '-', 'f24': 0.0, 'f25': 0.0, 'f26': 20200623, 'f37': '-', 'f38': '-', 'f39': '-', 'f40': '-', 'f41': '-', 'f45': '-', 'f46': '-', 'f48': '-', 'f49': '-', 'f57': '-', 'f61': '-', 'f100': '-', 'f112': '-', 'f113': '-', 'f114': '-', 'f115': '-', 'f221': '-'}]
(Background on this error at: https://sqlalche.me/e/20/9h9h)
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 5.1817467212677 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 18:00:16.742119 #######
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.21419811248779297 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 18:01:55.891926 #######
ERROR fetch_stocks.py:23 fetch_stocks¥¶¿Ì“Ï≥££∫'dict' object has no attribute 'filter'
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.16850900650024414 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 18:11:21.901253 #######
ERROR fetch_stocks.py:23 fetch_stocks¥¶¿Ì“Ï≥££∫'dict' object has no attribute 'filter'
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.1628713607788086 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 18:13:13.700609 #######
ERROR fetch_stocks.py:24 fetch_stocks¥¶¿Ì“Ï≥££∫'dict' object has no attribute 'filter'
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.17639470100402832 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 18:13:31.937783 #######
ERROR fetch_stocks.py:24 fetch_stocks¥¶¿Ì“Ï≥££∫'dict' object has no attribute 'filter'
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.7344300746917725 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 18:14:02.247879 #######
ERROR fetch_stocks.py:24 fetch_stocks¥¶¿Ì“Ï≥££∫'dict' object has no attribute 'f2'
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 0.7028093338012695 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 18:14:15.867399 #######
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 3.598893880844116 √Î #######
INFO execute_daily_job.py:28 ######## »ŒŒÒ÷¥–– ±º‰: 2024-05-16 18:15:54.105812 #######
INFO execute_daily_job.py:33 ######## ÕÍ≥…»ŒŒÒ,  π”√ ±º‰: 3.5545599460601807 √Î #######
